# Copyright 2016, Jarsa Sistemas, S.A. de C.V.
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).

{
    'name': 'Jarsa Freight Management',
    'version': '15.0.0.0.0',
    'category': 'Transport',
    'author': 'Jarsa Sistemas, Argil Consulting',
    'website': 'https://www.jarsa.com.mx/page/transport-management-system',
    'depends': [
        'account_operating_unit',
        'fleet',
        'hr',
    ],
    'external_dependencies': {
        'python': [
            'sodapy',
            'num2words',
            'responses',
        ],
    },
    'summary': 'Management System for Carriers, Trucking and other companies',
    'license': 'LGPL-3',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/tms_view.xml',
        'data/ir_sequence_data.xml',
        'data/account_journal_data.xml',
        'views/hr_employee_view.xml',
        'views/fleet_vehicle_view.xml',
        'views/fleet_vehicle_log_fuel_view.xml',
        'views/fleet_vehicle_log_fuel_prepaid_view.xml',
        'views/tms_event_view.xml',
        'views/tms_expense_view.xml',
        'views/tms_expense_line_view.xml',
        'views/tms_expense_loan_view.xml',
        'views/tms_factor_view.xml',
        'views/tms_place_view.xml',
        'views/tms_route_view.xml',
        'views/tms_transportable_view.xml',
        'views/tms_travel_view.xml',
        'views/tms_waybill_view.xml',
        'views/tms_extradata_view.xml',
        'views/account_move_view.xml',
        'views/tms_route_tollstation_view.xml',
        'views/fleet_vehicle_engine_view.xml',
        'views/tms_route_note_view.xml',
        'data/product_product_data.xml',
        'wizards/account_payment_register_view.xml',
        'wizards/tms_wizard_invoice_view.xml',
        'report/travel_instructions_letter.xml',
        'report/expense_report.xml',
        'data/ir_config_parameter.xml',
        'views/fleet_vehicle_log_services_view.xml',
    ],
    'demo': [
        
    ],
    'application': True,
    'installable': True,
}
